### ISSUE TITLE
Apply README update in develop branch to master branch

### ISSUE THREAD

**Issue by Liooo** [3logic/apollo-cassandra#14]
Currently the instruction says

`npm install apollo`

which probably is the older version of this app and is still valid in npm repository.
It's really confusing, and lots of potential users might get away since this is the entry point.

Looks like it's fixed in develop branch, so no matter what the latest state in the branch is, it's better to be immediately merged to master I think!

**Comment by ecogodi** [comment]
Fixed in 1.0.5
