### ISSUE TITLE
Not able to pass page state 'pageState' in find query

### ISSUE THREAD

**Issue by senthilkumar-sh** [3logic/apollo-cassandra#38]
I am trying to pass the pageState to maintain my current pagination page. I am unable to pass the value in my find query.

**Here is my find Query :** 

models.instance.Person.eachRow({pageState: 2, allow_filtering: true, autoPage : true, fetchSize : 10}, function(n, row){

**Error:**

{ apollo.model.find.dberror: Error during find query on DB -> TypeError: "list" argument must be an Array of Buffers

and in the result i always get 'pageState: null'

Please fix this or let me know is there any other way to solve this

**Comment by ramiel** [comment]
Hi @senthilkumar-sh.
This project is not maintained anymore so we cannot provide support on it, sorry. I was pretty sure we wrote it in the readme but it's not like this. I just fixed it.
You can find in the readme some alternatives.
Thank you for using apollo.
