### ISSUE TITLE
Share apollo connection

### ISSUE THREAD

**Issue by elmalto** [3logic/apollo-cassandra#7]
When I use mongoose, I can just require mongoose and add_models etc in seperate files and require it whenever necessary. Is this possible with apollo?

example:

var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var UserSchema = new Schema({...})

module.exports = mongoose.model('User',UserSchema);

and then I can just use var User = require(userfile.js) and use it ... I played around with apollo but could not figure it out...

**Comment by programming-kid** [comment]
what @elmalto saying here is right , in mongoose connection is established only once and it is then cached by mongoose and used everywhere in app,  and by doing what @ramiel  is saying we will have multiple connections open which will be really inefficient. One way to solve this will be to define schema and establish cassandra connection in one file which will get messy in long run.

database connection should be connected only once and shared by entire app. [refer here](http://stackoverflow.com/questions/28966901/mongoose-connection-automatically-shared-in-express-js-application)
